### ISSUE TITLE
Descendant of Attribute type does not seem to work

### ISSUE THREAD

**Issue by kaicode** [kaicode/srqs#2]
These should not return the same results:
http://localhost:8080/concepts?ecQuery=<<73211009:47429007=*
http://localhost:8080/concepts?ecQuery=<<73211009:<47429007=*

**Comment by amanlig** [comment]
HI @kaicode ,  does this still need work?

**Comment by kaicode** [comment]
@amanlig Yes, it still needs work. I've just corrected the queries in the example to make _47429007 |Associated with (attribute)|_ the attribute. I've rerun those against the July 2017 International release and the service gives the same 16 concepts back which is not correct.

**Comment by amanlig** [comment]
Thanks @kaicode. Can I have a shot at it and submit a fix?

**Comment by kaicode** [comment]
Hi @amanlig that would be very helpful, yes please!
Could I please ask that you include a unit test which supports your fix. That would make it easy for us to accept your work and will ensure that this bug doesn't happen again.
Many thanks.

**Comment by amanlig** [comment]
Will do add unit test with it.  Thanks @kaicode.

**Comment by mkaehlershs** [comment]
is it planned to fix this bug? In the current version this bug is still present:

**Comment by kaicode** [comment]
We are not proactively maintaining this project because our main ECL implementation is within the Snowstorm project and we only have limited capacity.
We are making some changes to this project related to our validation processes which use this as a library for MRCM validation.
We welcome contributions from the community for any bug fixes.

Kind regards,
Kai Kewley
